### ISSUE TITLE
Need to show both archetypes in selection drop down in correct order

### ISSUE THREAD

**Issue by AndrewSav** [Razzmatazzz/RemnantSaveGuardian#1]
In Remnant 2 we can change our archetypes and also we have one prime and one sub archetype. Both should be shown in the selection drop down in the correct order. I fired the game up, and it shows my sub archetypes only for both of my chars, I expected to see prime as a minimum, and both preferably.

**Comment by Razzmatazzz** [comment]
I don't know if it will be possible to fix this. I believe it currently shows the first archetype a user selected for that character.

**Comment by AndrewSav** [comment]
>  I believe it currently shows the initial archetype a user selected for that character.

This is inconsistent with what I'm seeing. I'm seeing the sub archetype, not the initial archetype I selected.

**Comment by Razzmatazzz** [comment]
I don't think I've gotten to the point where I can pick two archetypes yet. Can you export your save file as plaintext and post here?

**Comment by Wuxriff** [comment]
Actually it looks like this: my first char is hunter and his archetype currently is hunter too, but second arche is an Invader. Second char is hc\apoc hunter without any sub-arches. I'm digging it myself btw, but it's kinda hard. 

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/1228263/3e4c621b-e2f1-4278-8f60-caf502a943e4)
[profile.txt](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12195306/profile.txt)

**Comment by Razzmatazzz** [comment]
Try this test build:
[RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12195961/RemnantSaveGuardian.zip)

**Comment by Wuxriff** [comment]
> Try this test build: [RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12195961/RemnantSaveGuardian.zip)

Looks cool, 7b3967970ca2019baa65f432b4d0ae5ad684cde7 commit should close this issue 🙂
