### ISSUE TITLE
It won't run.

### ISSUE THREAD

**Issue by starbkh** [Razzmatazzz/RemnantSaveGuardian#10]
Are there any other files I need to download?

No response.
It's the same even if I turn off the antivirus program and run it.

**Comment by Razzmatazzz** [comment]
You need to install Microsoft's .NET framework.

**Comment by Razzmatazzz** [comment]
I'll add some error handling code to make it easier to figure out what's going on.

**Comment by DionysisReborn** [comment]
I'm also running into this. When I launch the app, I see a main process and a secondary process inside Task Manager, but the both close within about a second.

**Comment by DarthVocrum** [comment]
hello, the program seems to open normally but as soon as i click "world analizer" it crashes :S help!

**Comment by Razzmatazzz** [comment]
For anyone who the app seems to be instantly crashing: this build might stay alive and provide error messages:
[RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12234701/RemnantSaveGuardian.zip)

**Comment by DarthVocrum** [comment]
ye now it does not crash but theres like 100 lines of text and i am a complete retard when it comes to this stuff, why wont it work?

**Comment by Razzmatazzz** [comment]
100 lines of text where? In the log or in the world analyzer?

**Comment by DarthVocrum** [comment]
nvm dude im retarded like i said, i didnt select my current character now it works xD ty!!

**Comment by Razzmatazzz** [comment]
@starbkh @RAVVS @DionysisReborn does the latest release work for you, or at least stay open to display an error message?

**Comment by DionysisReborn** [comment]
> @starbkh @RAVVS @DionysisReborn does the latest release work for you, or at least stay open to display an error message?

It stayed open just fine. Crashed once when I selected the proper save folder, but when I opened it after that there have been no issues. Running great.

**Comment by gslinger** [comment]
Also wont run at all for me. I have the framework installed.
