### ISSUE TITLE
Display missing items as objects instead of strings

### ISSUE THREAD

**Issue by Razzmatazzz** [Razzmatazzz/RemnantSaveGuardian#103]
Currently, the missing items columns of the analyzer shows items as just a text string delimited with new line characters. Ideally, this column would display items as objects so tooltips could show the notes for each and right-clicking could show a menu similar to the missing items tab with options to visit the wiki, etc. that would make it so users wouldn't have to switch back and forth between the tabs to get all the info for an item. 

I don't have the time to figure this out, but if someone with the required expertise does, this would be a great feature for a PR.

**Comment by crackedmind** [comment]
Work in progress
https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/1381503/7c753624-8a62-4e54-8ccf-cd829c80977b

**Comment by Razzmatazzz** [comment]
Looking great so far!

**Comment by Razzmatazzz** [comment]
Completed in #120 by @ghostnup
