### ISSUE TITLE
1.0.1.15 Doesn't Run At All

### ISSUE THREAD

**Issue by DanMartin85** [Razzmatazzz/RemnantSaveGuardian#107]
Made sure game was open, ran the .exe, nothing happens. i dont even see it listed in resource manager. 

fresh release download.

Windows defender doesnt seem to be blocking it. no sure whats going on.

**Comment by Razzmatazzz** [comment]
If you grab 1.0.1.14 from the releases page, does that version work for you?

**Comment by DanMartin85** [comment]
nope that doesnt run either. Strange thing is i can see it greyed out under the memory section of the resource monitor. It looks like it gets terminated before it even runs. 

Is there somewhere i can pull a log for you?

**Comment by Razzmatazzz** [comment]
Have you installed Microsoft .NET 6.0 or greater?
https://dotnet.microsoft.com/en-us/download

**Comment by DanMartin85** [comment]
reinstalled. and now it works. 

I doubled checked that i had 6.0 LTS as i was able to create VS2022 projects with 6.0 framework. guess i didnt have it fully installed. I dont know. seems to be running now.
