### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by Lukasbech** [Razzmatazzz/RemnantSaveGuardian#11]
Just installed .NET 7, but I can't seem to figure out how to start the program. Which file should I open to start it? And is anything else needed to make it run?

Thank you in advance

**Comment by Razzmatazzz** [comment]
RemnantSaveGuardian.exe

**Comment by dmjtkj** [comment]
I was so excited to see this file and then I had the same question as Lukasbech... and unfortunately my download zip does not have an .exe file lol.  Any other options? I have net 7 installed and have tried opening a ton of files but nothing has worked so far.  
 
Closest I have is a .csproj file?

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/140994929/56b031cf-d679-4cbd-b9e0-fae293274e78)

**Comment by crackedmind** [comment]
You dowloaded sources, check releases page https://github.com/Razzmatazzz/RemnantSaveGuardian/releases/tag/1.0.0.3
