### ISSUE TITLE
Adventure tab don't work

### ISSUE THREAD

**Issue by crackedmind** [Razzmatazzz/RemnantSaveGuardian#114]
Don't work for yesterday save after this commit https://github.com/Razzmatazzz/RemnantSaveGuardian/commit/41f6d0f8a33d8353e59241816769370029257aed
[save.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12380877/save.zip)

But if i recreate adventure - adventure tab works

**Comment by GitBooSTid** [comment]
I have the same issue with today's commit, adventure tab can no longer be clicked on

**Comment by Razzmatazzz** [comment]
I've been testing some improvements today, and this build seems to load that adventure tab fine:
[RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12384386/RemnantSaveGuardian.zip)

**Comment by GitBooSTid** [comment]
Confirmed, works for me. And "The Chimney" is in there correctly now too :)
