### ISSUE TITLE
Error while trying to use World Analyzer

### ISSUE THREAD

**Issue by freeman211986** [Razzmatazzz/RemnantSaveGuardian#116]
This is the error log:

Error loading world Data in CharacterData.LoadWorldData: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')    at RemnantSaveGuardian.RemnantWorldEvent.ProcessEvents(RemnantCharacter character, String saveText) in C:\Users\Dan\source\repos\RemnantSaveGuardian\RemnantSaveGuardian\RemnantWorldEvent.cs:line 1645
   at RemnantSaveGuardian.RemnantWorldEvent.ProcessEvents(RemnantCharacter character) in C:\Users\Dan\source\repos\RemnantSaveGuardian\RemnantSaveGuardian\RemnantWorldEvent.cs:line 1652
   at RemnantSaveGuardian.RemnantCharacter.LoadWorldData() in C:\Users\Dan\source\repos\RemnantSaveGuardian\RemnantSaveGuardian\RemnantCharacter.cs:line 160

**Comment by Razzmatazzz** [comment]
Please post your save files here.

**Comment by freeman211986** [comment]
[1026825272.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12385277/1026825272.zip)

Hope this is fine (I'm new to github). 
Also, thanks for your work!

Probably unrelated, but maybe worth mentioned: I have custom locations for my Desktop and My Documents folders.

For example, standard location of My Documents would be: C:\Users\My user name\Documents
When in fact, my location is something like: F:\custom folder\Documents
Similar thing applies to Desktop folder.
I changed both of them because of HDD space issues on C (long story)

Also maybe worth mentioned, Steam install location is on a partition (F), while Steam game install location is on another partition (E). But settings are fine for Remnant Save Guardian.

![set](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/142638139/e5252350-8a79-4104-99e0-d5b904e22059)
