### ISSUE TITLE
World Analyzer incorrect in both Campaign & Adventure

### ISSUE THREAD

**Issue by rektosaurusrekts** [Razzmatazzz/RemnantSaveGuardian#117]
No matter which Remnant Save Guardian I use both the campaign and adventure are listing the incorrect places for my soft core character. My hardcore character is otherwise completely fine and displays the correct locations and items properly. As an example the save guardian is displaying N'Erud for my adventure mode even though I'm in Yaesha. I've attached my latest backup to help analyze what's wrong. 
[638279882687683654.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12384631/638279882687683654.zip)
![Untitled](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/113574885/737f32a5-4560-4c45-b95a-7fe322d439a5)

**Comment by rektosaurusrekts** [comment]
I forgot to mention it also shows my campaign incorrectly, even if I reroll for N'Erud seekers which always spawns Shal Hala it displays Tal Ratha no matter what, and the entirity of the campaign section is incorrect as well. The save guardian used to work until one day it didn't and it may be when I "restored" a backup. 

![Annotation 2023-08-18 205947](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/113574885/d661f2a0-2eb1-4d00-9e0b-5307ccb35801)

**Comment by Razzmatazzz** [comment]
Just looking at the files you sent me, I'd say this is your problem:
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/35779878/d11b6cfa-3c9a-4096-a82b-c51e6774714c)
Those extra world save files are messing you up.

**Comment by rektosaurusrekts** [comment]
oh thanks a lot for showing me that! Which one's should I delete then o.o?

**Comment by Razzmatazzz** [comment]
The top two save_0 files that are named weird.

**Comment by rektosaurusrekts** [comment]
Thank you so much, that worked! I was using a manual method to backup saves
before I figured out how to use the restore function on remnant save
guardian.

**Comment by Razzmatazzz** [comment]
Ok, glad it's working for you now. FYI, those extra files are probably in all of your backup folders, so if you restore a backup, they will return.
