### ISSUE TITLE
The latest version is not working properly

### ISSUE THREAD

**Issue by Rahat47313** [Razzmatazzz/RemnantSaveGuardian#119]
Version [1.0.2.2] is giving me error (in the screenshot) 
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/82301973/8315a29a-5294-4813-bc5b-7700c5fd07af)

And when I tried to run the previous version, its not giving me any errors

**Comment by crackedmind** [comment]
Can you enable Settings->Create log file, restart application and upload log.txt from application folder here?

**Comment by Rahat47313** [comment]
[log.txt](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12385284/log.txt)

**Comment by liuloic** [comment]
Hello, same thing for me 

Here's my log file 

[log.txt](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12385611/log.txt)

**Comment by Razzmatazzz** [comment]
@Rahat47313  @liuloic Can one of you confirm this build works?
[RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12385757/RemnantSaveGuardian.zip)

**Comment by WimOfAstora** [comment]
I just downloaded and installed the File in the above post. I still get the same errors / logs as two lads above me.

**Comment by liuloic** [comment]
Same as @WimOfAstora 

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/7439049/2f9b141e-11fb-450a-a111-57070b515fdc)

**Comment by Rahat47313** [comment]
still gives error:
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/82301973/a528dfef-492b-4cfc-8018-de3ee58e99d6)
[log.txt](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12386134/log.txt)

**Comment by crackedmind** [comment]
Can you add your save files?

**Comment by Rahat47313** [comment]
> 
[save_0.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12386394/save_0.zip)

**Comment by WimOfAstora** [comment]
[save_0.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12386443/save_0.zip)

**Comment by WimOfAstora** [comment]
Update. I didnt do anything special in the meantime but playing with randoms and re-rolling my campaing multiple times with different difficulties.  Magic : the World Analyzer is back online. I get the feeling the save games are sometimes somehow corrupted.

**Comment by FarMoreBlue** [comment]
Is it possible that using the program while playing can cause issues? I got the same errors as those above after leaving it running and re-rolling my campaign. I reverted to a backup save from about 10 minutes prior, re-rolled my campaign, closed the game, then used the program without issues.

**Comment by Razzmatazzz** [comment]
I need someone to post their full save (including profile) so I can troubleshoot this.

**Comment by Rahat47313** [comment]
> 

[save files.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12388641/save.files.zip)

**Comment by hratgard** [comment]
I have the same error as others are reporting here.
But I before it bugged out, I also noticed in N'erud when ever a dungeon the Stargazer ring, the analyzer would claim the dungeon had the Kinetic Shield Exchanger. Never was able to find the KSE in any of these, but did always find the Stargazer. - At least I needed both initially.. :D

**Comment by Razzmatazzz** [comment]
This build fixes the error:
[RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12390636/RemnantSaveGuardian.zip)

**Comment by Razzmatazzz** [comment]
> I have the same error as others are reporting here. But I before it bugged out, I also noticed in N'erud when ever a dungeon the Stargazer ring, the analyzer would claim the dungeon had the Kinetic Shield Exchanger. Never was able to find the KSE in any of these, but did always find the Stargazer. - At least I needed both initially.. :D

AFAIK, KSE is akin to other random trinket drops and should only show up if present. The only way I know that it differs is that the event is named "Amulet_01" instead of being named after the amulet that it spawns.
