### ISSUE TITLE
Bosses showing incorrectly in world analzyer

### ISSUE THREAD

**Issue by MattSr92** [Razzmatazzz/RemnantSaveGuardian#12]
A line is shown indicating the world boss for Yaesha and Losomn, but not N'Erud.
Also have seen sometimes Yaesha shows both world bosses.
Submitted using v1.0.0.3.

[profile.txt](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12210240/profile.txt)
[save_0.txt](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12210241/save_0.txt)

[save_0 (1).txt](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12210243/save_0.1.txt)
[profile (1).txt](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12210245/profile.1.txt)

Edit: Found that N'Erud does show a boss line for the Guardian, but not the alternate world boss.

**Comment by SpikyKnight** [comment]
At least in this case you can figure out which boss you have by a map layout or a starting location name.

**Comment by Razzmatazzz** [comment]
This should be fixed or greatly improved with the latest release.
