### ISSUE TITLE
How is the Remnant2 .sav encrypted?

### ISSUE THREAD

**Issue by Fnober** [Razzmatazzz/RemnantSaveGuardian#124]
Hi developers, I want to decode save_0.sav to plain text, so I read part of the project code and found that you should use ZLibStream to decompress the bytes stream in memory, but I am not good at C#. So I tried to use zlib.decompress in Python and couldn't make any progress. So I was wondering what kind of special treatment do you do?

**Comment by aescolastico** [comment]
its not encrypted. 

@crackedmind provided the unpacking code

heres the script he made: https://gist.github.com/crackedmind/3c7b63811afaafc4bdd4f8cb8319c1d0

**Comment by Fnober** [comment]
Thanks，I think this tool solves my problem：
https://github.com/AndrewSav/r2recompress
