### ISSUE TITLE
Language selection

### ISSUE THREAD

**Issue by tiramisu0101** [Razzmatazzz/RemnantSaveGuardian#126]
1.0.2.2，No option for simplified Chinese

**Comment by tiramisu0101** [comment]
Traditional Chinese only

**Comment by ghostnup** [comment]
Yep, I've commited a PR to fix this #125

**Comment by ghostnup** [comment]
> > 是的，我已经提交了一个 PR 来修复这个问题#125
> 
> When will it be updated

Next release i think, PR has been merged. Just wait for Razzmatazzz to release a new version, please be patient.

**Comment by tiramisu0101** [comment]
> 

OK！thanks～

**Comment by Razzmatazzz** [comment]
Yep, new release includes this fix. Thanks, @ghostnup!
