### ISSUE TITLE
RemnantSaveGuardian Causes Application Crashes and Visual Glitches

### ISSUE THREAD

**Issue by HarshWinter101** [Razzmatazzz/RemnantSaveGuardian#132]
Love this app and the app from the first game but since a recent update, whenever I open Remnant Save Guardian, the application frame rate drops drastically, constantly causes my screen to go black, and crashes apps such as discord and Remnant 2. As soon as I close the Remnant Save Guardian App my computer returns to normal and runs smoothly. let me know if there's any other details I can give, if it helps solve the issue.

**Comment by Razzmatazzz** [comment]
Does this happen anytime the app is running, or only if you've loaded the world analyzer page?

**Comment by Razzmatazzz** [comment]
Also, which release started these issues for you?

**Comment by HarshWinter101** [comment]
It happens any time the app is running. And the update it started happening was version 1.0.1.5.
And the version i first installed was 1.0.1.2. But when i relaunched that version just now i got the same issue the updated ones have.

Interestingly after i opened 1.0.1.2 again to double check the version for this post, the fps was fine but my pc bluescreened and now after the bluescreen i can run 1.0.1.5  and the latest versions without the blackscreening or window popping.

The only thing i notice is the fps of my screen is still lower than my native desktop while the RemnantSaveGuardian is the active window tabbed into window

**Comment by Razzmatazzz** [comment]
Honestly it sounds like your GPU is dying or your computer has some other pre-existing issues.

**Comment by HarshWinter101** [comment]
My pc normally runs everything fine but i do think its probably more an issue on my end with something else clashing with the application. And the bluescreen seemed to fix my main issues with the app haha. Anyway thanks for hearing out my issues
