### ISSUE TITLE
"Unrecognized files found in save folder"

### ISSUE THREAD

**Issue by doodirock** [Razzmatazzz/RemnantSaveGuardian#134]
I'm getting a new warning with the latest version that states 

> Unrecognized files found in save folder

It then lists all the actual saves files in my folder as the unrecognized files.  I'm not sure if this means they are corrupt or if there is another issue but my game seems to play fine.

**Comment by Razzmatazzz** [comment]
Did you manually copy or place any additional save files in your save folder?

**Comment by seanasaur** [comment]
> I am receiving the same message. It is listing all the files in my saves folder. I haven't made any edits to this folder
> 
> ![image](https://user-images.githubusercontent.com/142841593/262143642-9f37f6ad-3c94-416c-a6d7-1b63256300d7.png)


It is specifically happening when creating a backup of the world save.

**Comment by doodirock** [comment]
> > I am receiving the same message. It is listing all the files in my saves folder. I haven't made any edits to this folder
> > ![image](https://user-images.githubusercontent.com/142841593/262143642-9f37f6ad-3c94-416c-a6d7-1b63256300d7.png)
> 
> It is specifically happening when creating a backup of the world save.

Yep, exact issue

**Comment by Razzmatazzz** [comment]
Looks like I need to add some more filenames to the whitelist. I added this notice because some people were manually copying save files into their save folder and it was messing up the world analyzer.

**Comment by doodirock** [comment]
> u

Makes sense.  I haven't added any of these files so its whatever has come from the standard install.
