### ISSUE TITLE
Enhancement request: Labyrinth and Root Earth

### ISSUE THREAD

**Issue by Malidictus** [Razzmatazzz/RemnantSaveGuardian#139]
Is it possible to include items from the Labyrinth and Root Earth instances in a given campaign, similar to items on Earth? Currently, only Losomn, N'erud, Yesha and Earth items are showing. It would be convenient to see if I've missed anything in either the Labyrinth or Root Earth.

**Comment by aescolastico** [comment]
They should be there already. Here's RSG for a new character: 
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/30540257/b74bc500-4869-491d-8c2c-378306759fae)

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/30540257/fc466cfb-6451-4107-bce2-6c970524f629)

**Comment by Razzmatazzz** [comment]
Like the other Ward 13 events, they're hidden if a character already has all the possible items for a given event.
