### ISSUE TITLE
Gorge boss not in the right location

### ISSUE THREAD

**Issue by Esperadoce** [Razzmatazzz/RemnantSaveGuardian#146]
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/5134964/6148d270-f69d-4ac6-93ca-8eac59971cf1)
I'm not sure but I think that's a mistake 
George boss only exist in the Butcher’s Quarters or the Cotton Kiln I don't understand why it appear here.

**Comment by Razzmatazzz** [comment]
Please post your save files in #45
