### ISSUE TITLE
[Feature request] update from the program

### ISSUE THREAD

**Issue by MegaClinton** [Razzmatazzz/RemnantSaveGuardian#150]
Instead of having to redownload the program everytime there's a new update, maybe have a connection to the github version and let it auto update from within the program itself.

**Comment by crackedmind** [comment]
@Razzmatazzz https://github.com/Squirrel/Squirrel.Windows what do you think?

**Comment by crackedmind** [comment]
If you will write good update system...

**Comment by Razzmatazzz** [comment]
I love pull requests, and if someone wants to write a PR that automates updating the app, I'm all for it.
