### ISSUE TITLE
[Feature Request] Add an editable column to the Backup UI

### ISSUE THREAD

**Issue by studdugie** [Razzmatazzz/RemnantSaveGuardian#167]
My primary use case for this request is so that I can label the backups with something meaningful. For example, if I have a backup that I want to keep forever of an event, or injectable, or item, or boss I  can put a label or comment so I know what the backup is. Thanks.

**Comment by Razzmatazzz** [comment]
This already exists; the "Name" column is editable and you can change it to whatever you want. It just defaults to the integer timeteamp of the date of the save.
