### ISSUE TITLE
Newest Patch Due To Corrupted Weapons Addition Now Causes Missing Items To Show That You're Missing That Weapon When It's Converted To Corrupted

### ISSUE THREAD

**Issue by Melabones** [Razzmatazzz/RemnantSaveGuardian#173]
I'm aware the patch is just released and obviously the analyzer won't be updated right a way but due to the newest patch that has added the new corrupted weapons option those weapons that you convert to corrupted weapons will now show the uncorrupted version as a missing weapon. Example when converting Deceit to Corrupted Deceit the analyzer will show Deceit as missing. Maybe if possible have the analyzer not show that Regular Deceit is missing if player currently has Corrupted Deceit in inventory and vice versa when converting Corrupted Deceit back to Regular Deceit since you can only have one version at a single time. Probably not a big deal but just a thought.

**Comment by AndrewSav** [comment]
If you can have both Deceit and Corrupted Deceit, and you only have Corrupted Deceit then Deceit is obviously missing. I don't know if you can have both. Do you?

**Comment by Melabones** [comment]
Never mind found out you can obtain both regular and corrupted you just have to gather the same crafting materials as before to craft regular weapon

**Comment by Melabones** [comment]
When I first converted the weapon with Dwell you could convert it to Corrupted and revert it back to regular. So I believed that because of that you could only have one version of the weapon at a time. But found out that you can have both versions. You just have to gather the crafting materials to recraft the regular version once you convert it to corrupted. So the analyzer showing the regular version would still be correct. The DEVs aren't really good with giving us details on the new stuff added.

**Comment by AndrewSav** [comment]
> The DEVs aren't really good with giving us details on the new stuff added.

No they are not. I think that's intentional, and the company's philosophy that the players should enjoy discovering things themselves.
