### ISSUE TITLE
Many missing items?

### ISSUE THREAD

**Issue by identity7** [Razzmatazzz/RemnantSaveGuardian#199]
I definitely don't have all the DLC items yet, but RSG isn't listing any DLC items as missing nor is it listing any in the campaign/adventure tabs(minus the mutations). i do have the latest release of RSG
![Capture](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/85660015/f9423565-5468-4746-974c-caa55e41307f)

**Comment by MrWastedPanic** [comment]
The DLC items have not been added yet. It's being worked on as we speak
