### ISSUE TITLE
World analyzer not detecting adventure world?

### ISSUE THREAD

**Issue by AlexSFeather** [Razzmatazzz/RemnantSaveGuardian#2]
not sure if its still not capable of scanning for adventure worlds yet or it didnt detect mine so thought i would ask here

**Comment by AndrewSav** [comment]
Yes, same here

**Comment by Razzmatazzz** [comment]
I didn't see the option to roll an adventure world yet, so I wasn't able to add that part. If someone with an adventure world can export their save files via the button on the world analyzer page and post here, that would be very helpful.

**Comment by CrimtS** [comment]
Sure, here's my world with adventure on Yaesha
[save_0.txt](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12193978/save_0.txt)
[save_1.txt](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12193980/save_1.txt)
[profile.txt](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12193981/profile.txt)

**Comment by Razzmatazzz** [comment]
Thanks! Is it your first or second character who has the adventure on Yaesha?

**Comment by crackedmind** [comment]
> I didn't see the option to roll an adventure world yet, so I wasn't able to add that part. If someone with an adventure world can export their save files via the button on the world analyzer page and post here, that would be very helpful.

Adventure mode will appear after completion first world.

**Comment by Razzmatazzz** [comment]
I just committed a change that I think should support adventure mode. Here's a test build:

[RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12194714/RemnantSaveGuardian.zip)

**Comment by CrimtS** [comment]
Some feedback about adventure mode update. 
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/54284301/1c1c3acf-3b01-4a30-90be-1746c4a012ad)
It is split form the campaign, but other world objects are still in the list somehow (only Injectable/POI types, i think). Also dungeons duplicate with _POI as you can see

**Comment by Razzmatazzz** [comment]
From what I can tell, this is the chunk for your adventure roll:
```/Game/World_Jungle/Quests/Quest_Story_Ravager/Quest_Story_Ravager.Quest_Story_Ravager    l   /Game/World_Fae/Quests/Quest_OverworldPOI_TheHunter/Quest_Global_TheHunterDream.Quest_Global_TheHunterDream    i   /Game/World_Fae/Quests/Quest_Injectable_GoldenHall_Nimue/Quest_Global_NimueDream.Quest_Global_NimueDream    k   /Game/Campaign_Main/Quests/Quest_RootEarth_Zone2/Quest_Global_RootWalkerDream.Quest_Global_RootWalkerDream    h   /Game/World_Jungle/Quests/Quest_Miniboss_RootHorror/Quest_Miniboss_RootHorror.Quest_Miniboss_RootHorror    u   /Game/World_Jungle/Quests/Quest_SideD_CathedralOfSeasons/Quest_SideD_CathedralOfSeason.Quest_SideD_CathedralOfSeason    n   /Game/World_Jungle/Quests/Quest_OverworldPOI_Flautist/Quest_OverworldPOI_Flautist.Quest_OverworldPOI_Flautist    ?   /Game/World_Jungle/Quests/Quest_Event_Ring_RingOfTheForestSpirit/Quest_Event_Ring_RingOfTheForestSpirit.Quest_Event_Ring_RingOfTheForestSpirit    h   /Game/World_Jungle/Quests/Quest_Miniboss_MotherMind/Quest_Miniboss_MotherMind.Quest_Miniboss_MotherMind    e   /Game/World_Jungle/Quests/Quest_SideD_WailingField/Quest_SideD_WailingField.Quest_SideD_WailingField    \   /Game/World_Jungle/Quests/Quest_SideD_TheLament/Quest_SideD_TheLament.Quest_SideD_TheLament    h   /Game/World_Jungle/Quests/Quest_OverworldPOI_Meidra/Quest_OverworldPOI_Meidra.Quest_OverworldPOI_Meidra    q   /Game/World_Jungle/Quests/Quest_Event_Ring_SpiritStone/Quest_Event_Ring_SpiritStone.Quest_Event_Ring_SpiritStone    q   /Game/World_Jungle/Quests/Quest_Event_TraitBook_Jungle/Quest_Event_TraitBook_Jungle.Quest_Event_TraitBook_Jungle    ?   /Game/World_Fae/Quests/Quest_OverworldPOI_TheHunter/Quest_Global_TheHunterDream_Template01.Quest_Global_TheHunterDream_Template01    q   /Game/World_Fae/Quests/Quest_Injectable_GoldenHall_Nimue/Quest_Global_NimueDream_POI.Quest_Global_NimueDream_POI    a   /Game/Campaign_Main/Quests/Quest_RootEarth_Zone2/Quest_Earth_Seabed_Ship.Quest_Earth_Seabed_Ship    ?   /Game/World_Jungle/Quests/Quest_Story_Ravager/Quest_Story_Ravager_Overworld_Zone1_Template01.Quest_Story_Ravager_Overworld_Zone1_Template01    ?   /Game/World_Jungle/Quests/Quest_Story_Ravager/Quest_Story_Ravager_Overworld_Zone2_Template01.Quest_Story_Ravager_Overworld_Zone2_Template01    [   /Game/World_Jungle/Quests/Quest_Boss_Ravager/Quest_Boss_Ravager_POI.Quest_Boss_Ravager_POI    }   /Game/World_Jungle/Quests/Quest_Event_Amulet_StalkersBrand/Quest_Event_Amulet_StalkersBrand.Quest_Event_Amulet_StalkersBrand       /Game/World_Jungle/Quests/Quest_SideD_CathedralOfSeasons/Quest_SideD_CathedralOfSeasons_POI.Quest_SideD_CathedralOfSeasons_POI    }   /Game/World_Jungle/Quests/Quest_Event_Amulet_VengeanceIdol/Quest_Event_Amulet_VengeanceIdol.Quest_Event_Amulet_VengeanceIdol    w   /Game/World_Jungle/Quests/Quest_Injectable_Islands_Tower/Quest_Injectable_Islands_Tower.Quest_Injectable_Islands_Tower    ?   /Game/World_Jungle/Quests/Quest_Event_Amulet_ScavengersBauble/Quest_Event_Amulet_ScavengersBauble.Quest_Event_Amulet_ScavengersBauble    ?   /Game/World_Jungle/Quests/Quest_Injectable_Island_BrokenTomb/Quest_Injectable_Island_BrokenTomb.Quest_Injectable_Island_BrokenTomb    z   /Game/World_Jungle/Quests/Quest_Event_Ring_HeartOfTheWolf/Quest_Event_Ring_HeartOfTheWolf.Quest_Event_Ring_HeartOfTheWolf    ?   /Game/World_Jungle/Quests/Quest_Injectable_Crypt_Sarcophagus/Quest_Injectable_Crypt_Sarcophagus.Quest_Injectable_Crypt_Sarcophagus    p   /Game/World_Jungle/Quests/Quest_Miniboss_RootHorror/Quest_Miniboss_RootHorror_POI.Quest_Miniboss_RootHorror_POI    p   /Game/World_Jungle/Quests/Quest_Miniboss_MotherMind/Quest_Miniboss_MotherMind_POI.Quest_Miniboss_MotherMind_POI    m   /Game/World_Jungle/Quests/Quest_SideD_WailingField/Quest_SideD_WailingField_POI.Quest_SideD_WailingField_POI    d   /Game/World_Jungle/Quests/Quest_SideD_TheLament/Quest_SideD_TheLament_POI.Quest_SideD_TheLament_POI```

As you can see, there's Losomn (Fae) and RootEarth stuff mixed in there. Not sure why.

**Comment by CrimtS** [comment]
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/54284301/51860a61-95c6-456d-b232-08fc5dc519f6)
Maybe Kaeula's rest is CathedralOfSeasons, otherwise something is wrong(just made a backup)

**Comment by Razzmatazzz** [comment]
I would expect CathedralOfSeasons to refer to the main boss/puzzle in that dungeon. The names for events in the save files don't always correspond closely with what you see in the game.

**Comment by Razzmatazzz** [comment]
Closing this as adventure now displays. Remaining issues are related to #6 and #9.
