### ISSUE TITLE
Tainted Blade and Fetid Wounds showing in Missing Items

### ISSUE THREAD

**Issue by MrWastedPanic** [Razzmatazzz/RemnantSaveGuardian#200]
I know version 1.2 just released but both Tainted Blade and Fetid Wounds mutators are showing as missing when I own them both. Not a big deal at all but just wanted to bring attention

**Comment by ExoZNiK** [comment]
I confirm that's happening to me too. i just downloaded the last version and i have obtained both the 2 mutators before, anyway still getting them as missing. Not a problem to ignore anyway but just saying to confirm the problem.

**Comment by YuhangTom** [comment]
Same problem for me.

**Comment by ExoZNiK** [comment]
Still present as missing in version program 1.2.1.0

**Comment by TheNasbit** [comment]
> Still present as missing in version program 1.2.1.0

@ExoZNiK 
This should not be the case if you have them on your character and are on the latest version. It is working fine for me, I own them as well. You may double-check the version and your character.
If it is the latest version and you have them in your inventory, could you please send us the .sav files, so we can investigate why this happen?

**Comment by ExoZNiK** [comment]
[saves.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/13444878/saves.zip)
the game is at the last version of steam as of now (397.429)

**Comment by TheNasbit** [comment]
@Razzmatazzz Something might went wrong during release? 
When I use his save with my personal published version it works fine. When I use the tool from the release-page, it is not. 

Also some of the other changes made in 1.2.1.0 are also missing. It is basically 1.2.0.0 with just a version bump on release page, but the actual changes are missing?

**Comment by ExoZNiK** [comment]
so is not my save related problem? i hope to be of any help btw if there is something that was not fixed well indeed :)

**Comment by TheNasbit** [comment]
> so it's not my save related problem? i hope to be of any help btw if there is something that was not fixed well indeed :)

Yes, your safegame is fine. 
Something went wrong during release process it seems, since all of the changes made in 1.2.1.0 are not present in the actual release.

**Comment by Razzmatazzz** [comment]
This is hopefully fixed in 1.2.2..0 which I just pushed out.

**Comment by YuhangTom** [comment]
> This is hopefully fixed in 1.2.2..0 which I just pushed out.

Thanks! Fixed for me.

**Comment by ExoZNiK** [comment]
Confirm that now is fixed. :)

**Comment by MrWastedPanic** [comment]
Works great in the latest version
