### ISSUE TITLE
[feature request] List of all missing items

### ISSUE THREAD

**Issue by Malidictus** [Razzmatazzz/RemnantSaveGuardian#214]
Would it be possible to add a tab which lists all items available in the game regardless of world, difficulty or anything else, filtered down to just the items not yet acquired? Currently, it's hard to tell if I'm missing specific items because I can only learn about them if my world rolls a drop for them.

Obviously, this is not a major priority. It would just be convenient to be able to keep track of what I have yet to pick up overall.

**Comment by AndrewSav** [comment]
Like the missing items tab?

**Comment by Malidictus** [comment]
Yes, exactly like that! :)

OK, I sincerely apologise for this. I never noticed that tab, and it does everything I wanted. Thank you kindly, and feel free to disregard this request.
