### ISSUE TITLE
N'Erud missing in Campaign tab

### ISSUE THREAD

**Issue by LuisBurdallo** [Razzmatazzz/RemnantSaveGuardian#22]
I am attaching the files. For some reason this new map isn't showing in campaign. I hope this is not another duplicate. :)

[Remnant2_N'Erud_Missing_Export_Files.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12254997/Remnant2_N.Erud_Missing_Export_Files.zip)

**Comment by Razzmatazzz** [comment]
Would you please export again using the latest 1.0.1.3 version? That will include the normal .sav files that I can easily load in and test. Thanks.

**Comment by LuisBurdallo** [comment]
Latest version seems to be loading the world just fine. Will check if there are any inconsistencies. Thanks.
