### ISSUE TITLE
Let us write a description for a save

### ISSUE THREAD

**Issue by igromanru** [Razzmatazzz/RemnantSaveGuardian#226]
The first thing that came to my mind as I marked a save backup for "Keep" is to describe the state of the game.  
There is already a nice long column on the right side that is empty.  
It would be really cool if we could edit it.  
Technically, since each save backup has it's won folder you could create a "description.txt" or a txt file with the name ID as file name in the directory of the save,

**Comment by Razzmatazzz** [comment]
You see the column called "name" just double-click in there and give the save any name you want.
