### ISSUE TITLE
world analyser not updating

### ISSUE THREAD

**Issue by lelouchTzero** [Razzmatazzz/RemnantSaveGuardian#231]
on adventure tab it says losomn no mater how many times i reroll even tho i have nerud

**Comment by Frohlemageblanc** [comment]
You need to actually load into your adventure for it to show.

**Comment by lelouchTzero** [comment]
> Not a bug : you need to actually load into your adventure for it to show.

First thing I did its how i knew it was a problem

**Comment by Frohlemageblanc** [comment]
Very weird, never happened to me. Could you share your save ?

**Comment by lelouchTzero** [comment]
> Then it seems to be a bug. Very weird, never happened to me. Could you share your save ?

not sure how to do that

**Comment by lelouchTzero** [comment]
![Uploading image.png…]()

**Comment by lelouchTzero** [comment]
> Then it seems to be a bug. Very weird, never happened to me. Could you share your save ?

do u think I need Microsoft .NET 6.0 downloaded? i didnt before but maybe something changed?

**Comment by lelouchTzero** [comment]
i somehow got it working think its something to do with the savefiles so just reset them and delete the save guardian and reinstall
