### ISSUE TITLE
Missing item list Shows Items I have

### ISSUE THREAD

**Issue by CamoGirmir** [Razzmatazzz/RemnantSaveGuardian#235]
Is it normal to see items I have on said List?

**Comment by TheNasbit** [comment]
Can U list the Items? Or is it ALL Items you already have?

**Comment by CamoGirmir** [comment]
Its a mix of things I have And things I don't like the full bruiser set even though I started as that class so I have it, or the Void heart which I'm currently using but also things I don't have Like The Meridian or other such things

**Comment by CamoGirmir** [comment]
Never mind seems I had a older version somehow its Fixed now
