### ISSUE TITLE
A search bar would be nice

### ISSUE THREAD

**Issue by LuceusW** [Razzmatazzz/RemnantSaveGuardian#24]
Sometimes it can be hard to look for a specific thing especially with campaign having so many lines of loot, locations and events.
Having a search bar would be of great help, that or being able to use CTRL+F

**Comment by Wuxriff** [comment]
Perhaps filtering would be better? If you are looking for a specific ring then there may be many options found and scrolling through the entire grid to see the highlighted ones can be... long a little.

**Comment by Shiranui-Izayoi** [comment]
Yer I think the ability to filter would be amazing. Since you already have the missing item tab. Maybe a filter tab similar to it where you can select various items and the list will only show those.

**Comment by Razzmatazzz** [comment]
Good idea. Added in latest release.

**Comment by AndrewSav** [comment]
@Razzmatazzz Hey, am I using it correctly? Here is, for example Feedback loop. 


![2023-08-05_14-16-48](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/658865/a3374f3c-7120-4357-aab5-9a7dc6488e5b)

I type Feed but nothing shown?

![2023-08-05_14-17-10](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/658865/1827661d-9492-4f2f-8463-df2c11ec3d54)

**Comment by AndrewSav** [comment]
Oh I see it's because it's not *missing* item. TBH I would find it more useful to filter by **all** columns: location, type, name, Possible items (if shown). May be a setting in settings if this is controversial?

**Comment by Shiranui-Izayoi** [comment]
It would be kinda cool if you could search all.

Either that or add the ability to favourite/mark certain items. They might then appear in a different colour for easy searching. 

Say I am looking for the game master ring as well as the star shot pistol and the Kolket's Razor to turn into the Nightweaver's Grudge in a campaign. I could mark them and they would show up differently from the other items. Maybe the missing item tab could be adjusted to be able to mark/favourite items.

**Comment by LuceusW** [comment]
Yeah, it would be better if we could filter anything and not just the missing items, pls

**Comment by Razzmatazzz** [comment]
This will be addd.
