### ISSUE TITLE
Error loading data after latest update + Adventure tab not accessible

### ISSUE THREAD

**Issue by TwentyGaugeHigh** [Razzmatazzz/RemnantSaveGuardian#244]
Getting the attached error when RSG tries to load data. Additionally, after the update today, the Adventure tab has become inaccessible.

The Missing Items list is also empty, though I figure that could be a product of the load error.

![rem_sg_save_error](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/101301548/aa27bdf5-6103-4947-adc4-80df63b52cdc)

**Comment by AdrianMusial** [comment]
I'm getting exactly the same error and the same problem with Advenure and Missing tabs.

**Comment by TwentyGaugeHigh** [comment]
> I'm getting exactly the same error and the same problem with Advenure and Missing tabs. EDIT: I rerolled adventure and the problem is gone. Now I'm not able to replicate it again. I tried to reroll all types of adventure and all is fine.

Thank you for the confirmation! I'll try to complete my adventure and reroll to see if I get the same resolution.

**Comment by TwentyGaugeHigh** [comment]
Rerolling adventure mode looks to have resolved the issue. The load error does not occur and the Adventure and Missing Items tabs are working as expected.
