### ISSUE TITLE
Any chance quest items could be displayed?

### ISSUE THREAD

**Issue by LitanyOfFire** [Razzmatazzz/RemnantSaveGuardian#27]
As per title, there are some items (some very difficult to get) that require certain quest or comination of quest items to spawn. Any chance they could be displayed along with other pickups?

**Comment by LitanyOfFire** [comment]
Nevermind I'm an idiot.

**Comment by AndrewSav** [comment]
I think they will be ignored for now https://github.com/Razzmatazzz/RemnantSaveGuardian/issues/9#issuecomment-1665582160
