### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by Lecassecouilles** [Razzmatazzz/RemnantSaveGuardian#275]
Hi.
Link for the lasted realase is broken on the main page but work on the realase page.

And thank you for your work :)

**Comment by Thangalang21** [comment]
Same here. Could be an incorrect pathway.

**Comment by ajknox** [comment]
Broken link: https://github.com/Razzmatazzz/RemnantSaveGuardian/releases/latest/download/RemnantSaveGuardian.zip
Working location: https://github.com/Razzmatazzz/RemnantSaveGuardian/releases/download/1.3.1/RemnantSaveGuardian_1.3.1.0.zip

**Comment by Razzmatazzz** [comment]
Fixed thanks to @milousparks .
