### ISSUE TITLE
Forgive me if I'm missing something obvious - Download missing .exe file to install

### ISSUE THREAD

**Issue by rangerdave9** [Razzmatazzz/RemnantSaveGuardian#284]
Hello, 
First off thank you for your efforts. I've used before but I'm a complete Novice when it comes to this sort of thing. 

When downloading the latest update for the Remnant Save Guardian program, I'm unable to find the RemnantSaveGuardian.exe file. What am I missing here? I'm sure there's a simple explanation for this. Would you mind sharing why I'm unable to find that in order to install?
![2024-09-30_4-27-59](https://github.com/user-attachments/assets/7f9fc167-c6d2-4eb3-967a-6a799ed64091)

**Comment by swedishjeff** [comment]
I know this was only opened 6 hours ago, and there are no other comments but, bump? I too, find the lack of an exe file disturbing.

**Comment by milousparks** [comment]
The Link on the README is broken at this time and it's normal that there is no executable inside the project. 
You can get the executable over the release page.
https://github.com/Razzmatazzz/RemnantSaveGuardian/releases/tag/1.4.1

**Comment by Razzmatazzz** [comment]
Fixed thanks to @milousparks 's PR.
