### ISSUE TITLE
add another language

### ISSUE THREAD

**Issue by chocosobo** [Razzmatazzz/RemnantSaveGuardian#3]
will app itself support multiple language this time?
or just edit files in locales folder and compile it?

**Comment by Razzmatazzz** [comment]
I built it to support multiple languages this time. The translation files are in RemnantSaveGuardian/locales. Strings.resx is for the interface and GameStrings.resx is for the world analyzer. To add support for a new language, you just need to make a copy of one of those files and rename the copy "Strings.de.resx" where "de" is the language code for the language you're adding. Then in the new file, change the value of all the data elements to the new translation. You can either submit new .resx files here or make a pull request and I'll add them in.

**Comment by crackedmind** [comment]
I can recommend Zeta Resource Editor for edit resx files outside Visual Studio.

**Comment by chocosobo** [comment]
[RSG.ko.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12233601/RSG.ko.zip)

translated menu first
item and thingy will translate soon

**Comment by Razzmatazzz** [comment]
Thanks for the translation! does this work for you?
[RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12234081/RemnantSaveGuardian.zip)

**Comment by chocosobo** [comment]
app shows english only

**Comment by Razzmatazzz** [comment]
Oof. Is your OS language set to Korean?

**Comment by chocosobo** [comment]
sure

**Comment by Razzmatazzz** [comment]
How about this one?
[RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12234216/RemnantSaveGuardian.zip)

**Comment by chocosobo** [comment]
still not work

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/6840644/3eb9451c-3407-488f-ab7d-334cabb6f6ce)

timer displaying korean but everything else doesnt

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/6840644/ff071865-51dc-4552-b92a-65e37197044c)




should show like this debug build

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/6840644/3f8aa0e8-919d-4281-b6ab-c5a9ad5c3059)

**Comment by Razzmatazzz** [comment]
Ok, this should work:

[RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12234478/RemnantSaveGuardian.zip)

**Comment by chocosobo** [comment]
yeap, it works fine

**Comment by Razzmatazzz** [comment]
Ok great, thanks for testing and thanks again for translating!

**Comment by ArthurGRX** [comment]
Hello, I would also like to help with localization into my own language (Ru), I translated the files (But I'm not quite sure about the format, the language is quite sweeping)
[Ru.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12251604/Ru.zip)

**Comment by Razzmatazzz** [comment]
Thank you for the translation! Does this version work properly for you?

[RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12251883/RemnantSaveGuardian.zip)

**Comment by ArthurGRX** [comment]
> Thank you for the translation! Does this version work properly for you?
> 
> [RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12251883/RemnantSaveGuardian.zip)

Localization works, I've tweaked the translation a bit since I saw it in action
[Ru.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12251991/Ru.zip)

**Comment by Razzmatazzz** [comment]
Thanks!
