### ISSUE TITLE
World Analyzer shows completely different areas?

### ISSUE THREAD

**Issue by sinnoaria** [Razzmatazzz/RemnantSaveGuardian#35]
I had withering wealds, but the analyzer shows other areas such as Faithless Thicket and different items.  I had Endaira's End, but the analyzer shows other areas such as The Chimney. I had Root Nexus, but Root Nexus also didn't show up.  It is like the analyzer is showing me the inverse of the area (the areas that aren't in my game are showing up in the analyzer). Except the world boss. The world boss seems to be correct (Might not be since I haven't reached it yet).

Edit: Looks like the areas listed are pretty random. two areas were the same. Could it maybe be analyzing the wrong save?

Edit2: This may be specific to HC Apoc mode.

Edit3: It seems like it could be showing my HC character world on my Normal character world. Will check again next reroll if coincidence or not.

Edit4/5/6/7/8: Changed the save files themselves to force my HC world as save_0 (from save_2. Put me in my first slot (save_0) world, but seems to have fixed things.) Maybe there can be a world swapper feature in the future?

Part of this was confusion because the names are different. Yaesha: Faithless Thicket in the guardian maps to Yaesha: The Forbidden Grove in my game, for example (There was ALSO a Faithless Thicket as well). I'm guessing it is because in Remnant 2, some items can show up in multiple areas and the guardian is reading the items instead of the areas). Also, campaign and adventure modes were swapped (still happening in 1.0.1.7)

Guardian crashes if I try to export the saves.

**Comment by AndrewSav** [comment]
Post your saves

**Comment by Razzmatazzz** [comment]
Yes, please use the export saves button on the world analyzer page and post the files here.

**Comment by Razzmatazzz** [comment]
This may work better with the latest release.
