### ISSUE TITLE
How can I change the language?

### ISSUE THREAD

**Issue by LinxinS97** [Razzmatazzz/RemnantSaveGuardian#36]
I notice that the software supports multiple languages, but when I open it, only English is activated, and I cannot find anywhere to change it.

**Comment by Wuxriff** [comment]
It depends on your current Regional format setting and currently you can't select anything manually. 
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/1228263/a911308d-c5d7-435f-a102-9e213113eb75)

I had plans to add this setting, but it all depends on the author of this repo.

**Comment by Razzmatazzz** [comment]
And it currently defaults to English if your OS language isn't available. Presently, there are translations for Korean, Russian, and Chinese.

**Comment by LinxinS97** [comment]
Thanks wuxriff！
Thanks razzmatazzz！
