### ISSUE TITLE
Shaed Bloom Crystal is marked as a ring, but it's an amulet

### ISSUE THREAD

**Issue by Wuxriff** [Razzmatazzz/RemnantSaveGuardian#37]
https://remnant2.wiki.fextralife.com/Shaed+Bloom+Crystal

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/1228263/78b0d80c-9b10-445f-844c-762c8a10aded)
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/1228263/1c6c0534-1a81-4d1f-8065-d9506eb966de)

**Comment by Razzmatazzz** [comment]
Where is it showing up as a ring? I believe that item's key is `/Items/Trinkets/Amulets/ShadeBloomFloret/Amulet_ShadeBloomCrystal`, so it should parse correctly to be recognized as an amulet.

**Comment by puffbro** [comment]
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/33358213/d86006c8-d4e2-4a5a-9a70-af3c59222d74)
I notice there's both "Amulet_ShadeBloomCrystal" and "Ring_ShaedBloomCrystal". But Shade bloom crystal amulet doesn't exist afaik.

**Comment by Wuxriff** [comment]
RSG says it's a ring and it's wrong. Also i discovered that Rebellion Spear isn't listed at all - and I don't have it in my current save. Missing entry in the game.json file perhaps.

**Comment by Razzmatazzz** [comment]
Yes, this will be fixed.

**Comment by Razzmatazzz** [comment]
This should be fixed in the latest release.

**Comment by Wuxriff** [comment]
Something went wrong.

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/1228263/ab7c658c-2089-4538-8324-6a5afc28a3f2)
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/1228263/96a3bc88-3478-45c0-906d-2201207b8c1b)
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/1228263/16d2b7e1-3c12-4ed7-bb87-d0e9a21059a7)
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/1228263/cc81018a-f5cf-45dd-bab7-da7ad311c13c)
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/1228263/0c688ef2-f7e9-4767-b3ae-36f4928fa459)

**Comment by Razzmatazzz** [comment]
Nothing went wrong. It just isn't pulling location names out of the save file in the same way because the locations were sometimes wrong in the old method. 

Now, some locations can be inferred from the events if the association exists in the game.json. But some events can occur in multiple locations. In that event, it uses the "SpawnTable" in the save file for the area name since it's usually somewhat descriptive of the area.

**Comment by Razzmatazzz** [comment]
Closing this as Shaed Bloom is fixed and the remaining discussion belongs in #9 .
