### ISSUE TITLE
Location column is empty

### ISSUE THREAD

**Issue by AndrewSav** [Razzmatazzz/RemnantSaveGuardian#4]
As on the screenshot:

![2023-07-28_21-46-00](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/658865/e3b89830-0247-4fbd-b944-23021059a447)

**Comment by Razzmatazzz** [comment]
Yep, that's because I don't have any information about which events appear in which locations yet. We've got to figure that out and do it manually.

**Comment by aescolastico** [comment]
@Razzmatazzz should that be crowdsourced? or would a better approach be to scrape the wiki?

**Comment by Razzmatazzz** [comment]
It's gotta be done manually.

**Comment by MattSr92** [comment]
@Razzmatazzz I think @aescolastico is asking if you'd want people to submit the information to a you in a central area, or if you're going to use the wiki.

**Comment by Razzmatazzz** [comment]
What's needed is an encyclopedia of all the events that appear in the game as seen in the game files and the corresponding items that drop from those events, also as seen in the game files. The wiki won't have the game file names for anything. All the names need to be pulled from saves.

**Comment by Wuxriff** [comment]
Like this one!

https://docs.google.com/spreadsheets/d/1e0SG36q9iMgGgu1yVnI6MqgDDuStYz5v4iU4UjFL3Yo/edit#gid=0

**Comment by aescolastico** [comment]
> Like this one!
> 
> https://docs.google.com/spreadsheets/d/1e0SG36q9iMgGgu1yVnI6MqgDDuStYz5v4iU4UjFL3Yo/edit#gid=0

No I dont think that will do. @Razzmatazzz just said they need the game file names. Not a spreadsheet with "friendly names".

**Comment by Wuxriff** [comment]
> > Like this one!
> > https://docs.google.com/spreadsheets/d/1e0SG36q9iMgGgu1yVnI6MqgDDuStYz5v4iU4UjFL3Yo/edit#gid=0
> 
> No I dont think that will do. @Razzmatazzz just said they need the game file names. Not a spreadsheet with "friendly names".

Yeah, but at least it's easier to check it via this table than through the wiki and manually dump items via CE. This table is still almost empty so it's useless. https://docs.google.com/spreadsheets/d/1IG4dX6ywBFZaMZIE_qyg7jNqyItb7QEvWb60Q-WTH-0/edit#gid=1709895928

**Comment by Wuxriff** [comment]
FModel is an option, we can dump everything using it 
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/1228263/9cea1773-0390-402f-a0f2-577b5cb07c75)
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/1228263/4ef7de43-1889-4f52-84db-a5049f2b3f5f)

**Comment by AndrewSav** [comment]
Just out of curiosity, how the Location column specifically worked for Remnant 1, and why the same way does not work for Remnant 2? I'm sure there are good reasons, just would like to understand them.
