### ISSUE TITLE
Suggestion: add alternative names to events in game.json

### ISSUE THREAD

**Issue by crackedmind** [Razzmatazzz/RemnantSaveGuardian#40]
For example
```
        {
          "name": "/Items/Armor/Nerud_Pilot/Armor_Head_PilotsHelm"
        },
```
game names this "[Navigator's helm](https://remnant2.wiki.fextralife.com/Navigator's+Helm)" and in wiki link to "pilot's helm" didnt work

**Comment by Razzmatazzz** [comment]
This is handled by the [translation strings](https://github.com/Razzmatazzz/RemnantSaveGuardian/blob/684edd2278a09c05f5385edd30a039e5ad73bef8/RemnantSaveGuardian/locales/GameStrings.resx#L384-L386).

**Comment by crackedmind** [comment]
> This is handled by the [translation strings](https://github.com/Razzmatazzz/RemnantSaveGuardian/blob/684edd2278a09c05f5385edd30a039e5ad73bef8/RemnantSaveGuardian/locales/GameStrings.resx#L384-L386).

I maybe misunderstood how it's works, but what about wiki links from missing items tab?

**Comment by Razzmatazzz** [comment]
The English translation string for that item is currently incorrect and can be fixed easily. It might be possible to force the wiki links to use the English values.

**Comment by crackedmind** [comment]
> The English translation string for that item is currently incorrect and can be fixed easily. It might be possible to force the wiki links to use the English values.

Good decision.
