### ISSUE TITLE
Add ability to view backups in world analyzer

### ISSUE THREAD

**Issue by Razzmatazzz** [Razzmatazzz/RemnantSaveGuardian#46]
I've tried incorporating this feature but have run into roadblocks due to my unfamiliarity with how the navigation model is supposed to work in the framework I'm using. If someone with more familiarity on how navigation works in the WPF UI framework wants to take a look, I can point you to the janky code I've already written to see if you know how to fix the problems.

**Comment by Razzmatazzz** [comment]
That would be amazing. For whoever gets to it first, here's a rundown of where things stand. Some of this is probably the absolute wrong way to do things.

The "view analyzer" context menu can be enabled by changing its visibility to `Visible` here:
https://github.com/Razzmatazzz/RemnantSaveGuardian/blob/4d3264b682c73f2b2a3f38ed0189e2d3741b6f3a/RemnantSaveGuardian/Views/Pages/BackupsPage.xaml#L64

When clicked, that menu option fires an event for the Backups page that provides the backup in question in the event arguments:
https://github.com/Razzmatazzz/RemnantSaveGuardian/blob/4d3264b682c73f2b2a3f38ed0189e2d3741b6f3a/RemnantSaveGuardian/Views/Pages/BackupsPage.xaml.cs#L123-L131

The main window listens for that event, and then attempts to add a new navigation item using a new instance the world analyzer page that loads the backup save's data:
https://github.com/Razzmatazzz/RemnantSaveGuardian/blob/4d3264b682c73f2b2a3f38ed0189e2d3741b6f3a/RemnantSaveGuardian/Views/Windows/MainWindow.xaml.cs#L150-L199

The main roadblock I've hit is that navigating to/from this new page seems buggy. Depending on how I try to do it, it appears to be just a duplicate of the existing world analyzer page or can't be selected. Or if I manage to select it via code, it's not possible to select it again after the user has navigated away from it.

**Comment by Wuxriff** [comment]
Thx, will take a look 👀

**Comment by Wuxriff** [comment]
Done 👀

**Comment by Wuxriff** [comment]
This is  something different. Will check for sure.

**Comment by Wuxriff** [comment]
After some research I came to the conclusion that I don't know how to make the Wpf.Ui framework display the 'selected tab' style while using NavigateExternal method, seems like it's impossible. Since you are using it and MVVM for some reason, then we could rewrite everything to real MVVM with events, but I would not want to do this.

I propose to replace RootNavigation.Navigate(pageTag); to RootNavigation.NavigateExternal(page); (as it was) and postpone until some future huge refactorings.

**Comment by Razzmatazzz** [comment]
That was the key! We can do `RootNavigation.NavigateExternal(page)` and `navItem.IsActive = true` and things function exactly how the user would expect. Thanks for taking a look at this!
