### ISSUE TITLE
Option to hide co-op only items

### ISSUE THREAD

**Issue by lloyd-delacroix** [Razzmatazzz/RemnantSaveGuardian#47]
The following rings and traits can only be obtained when playing in co-op. It could be helpful for players going for completion who can't / don't want to play online to have an option in the settings to hide them from the world analyzer missing items column and tab. Alternatively, they could be marked with something like "(Co-op Only)" and moved to a separate drop down similar to the hardcore only items.

Ring: Band Band
Ring: Band of Accord
Ring: Captains Insignia
Ring: Game Master's Pride

Trait: Glutton
Trait: Resonance
Trait: Revivalist

**Comment by Razzmatazzz** [comment]
This is being added in the next version.
