### ISSUE TITLE
Still not seeing archer's crest after 50 reloads

### ISSUE THREAD

**Issue by Rictaz** [Razzmatazzz/RemnantSaveGuardian#48]
Just reporting what I'm seeing, is it that rare?

**Comment by Razzmatazzz** [comment]
Nobody knows how common any event is. We're currently figuring out the conditions under which Archer's Crest is present, but it seems to spawn in some variation of the Hidden Maze event.

**Comment by Razzmatazzz** [comment]
Since #16 is primarily a discussion of Archer's Crest, I've renamed that issue to reflect that and am closing this issue.

**Comment by Rictaz** [comment]
I have it now if it can help, sitting in the map haven't picked it up yet

**Comment by Razzmatazzz** [comment]
Please try this test build and let me know if it shows up:

[RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12297161/RemnantSaveGuardian.zip)
