### ISSUE TITLE
vaccum seal ring 

### ISSUE THREAD

**Issue by NoobbyTV** [Razzmatazzz/RemnantSaveGuardian#49]
vaccum seal ring showing in incorrect location

**Comment by Razzmatazzz** [comment]
Please post a screenshot of what the analyzer shows as well as your save as exported from the world analyzer.

**Comment by NoobbyTV** [comment]
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/96333857/b1b6eeb0-5607-4140-9cf5-59722e4048f1)
showing phantom wasteland when im pretty sure that its nor in my world becasue phantom wasteland is a starting location and there 2 per world

**Comment by Razzmatazzz** [comment]
Please also post your save exported from the world analyzer as requested.

**Comment by NoobbyTV** [comment]
[profile.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12311992/profile.zip)
is that good

**Comment by Razzmatazzz** [comment]
Does that contain the same world you posted about? I don't see the Vacuum Seal Ring event anywhere.
