### ISSUE TITLE
Chrome/Windows Detecting Virus

### ISSUE THREAD

**Issue by mattr0d** [Razzmatazzz/RemnantSaveGuardian#5]
Chrome and Windows Defender are not happy with the release download just as a heads up. 

It's detecting Trojan:script/Wacatac.H!ml

**Comment by Razzmatazzz** [comment]
This was an issue with the Remnant 1 analyzer as well (https://github.com/Razzmatazzz/RemnantSaveManager/issues/41). It's a false positive and there's not a whole lot I can do about it afaik.
