### ISSUE TITLE
Unsure if missing, engineer engram

### ISSUE THREAD

**Issue by sinnoaria** [Razzmatazzz/RemnantSaveGuardian#53]
I've rerolled the world about 10-20 times now and have not seen the engineer engram pop up. I have seen the navigation ship pop up several times though. Does the analyzer currently not show the pick up engrams?

(Still can't export saves since it crashes.)

**Comment by Razzmatazzz** [comment]
The world analyzer doesn't show crafting ingredients; it shows the items those items can eventually be crafted into. I need someone with the Alien Device crafting material in their world to post their save so I can see if there's an event tied to it.

**Comment by Razzmatazzz** [comment]
I think I figured this out. Should be fixed in the next version.
