### ISSUE TITLE
RING OF THE DAMNED AND SEVERED HAND

### ISSUE THREAD

**Issue by NoobbyTV** [Razzmatazzz/RemnantSaveGuardian#55]
they dont track correctly so they basically dont show up the ring is attached to the hand

**Comment by Razzmatazzz** [comment]
If you have a save where you found the ring, please export it via the world analyzer and post it here.

**Comment by NoobbyTV** [comment]
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/96333857/c9d410c7-1d6d-4eee-a15a-5e5f40ec8f75)
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/96333857/b1b6eeb0-5607-4140-9cf5-59722e4048f1)
showing phantom wasteland when im pretty sure that its nor in my world becasue phantom wasteland is a starting location and there 2 per world

**Comment by NoobbyTV** [comment]
file fopr both vacuum seal and hand

**Comment by NoobbyTV** [comment]
[638271211082252773.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12300927/638271211082252773.zip)
files for both hand and vaccum seal oine is in adventure other one story

**Comment by Razzmatazzz** [comment]
Please export via the world analyzer and provide those files.

**Comment by NoobbyTV** [comment]
that what i did i think the file is here i dont have them anymore i click on backup this the file from the save guardian folder

**Comment by Razzmatazzz** [comment]
No, that's just a save backup. The export button is the up arrow to the right of the character selector on the world analyzer.

**Comment by Razzmatazzz** [comment]
Assuming you don't have the world any longer and can't export, please do export if it pops up again for you and post in #43 .
