### ISSUE TITLE
Band of Accord

### ISSUE THREAD

**Issue by matt-rod** [Razzmatazzz/RemnantSaveGuardian#56]
There is a ring called Band of Accord (which I have collected)

The analyzer is showing a missing item on Reggie called Ring_RingOfAccord.
I presume it's the same item but it appears the tracking is confused.

**Comment by Razzmatazzz** [comment]
Most likely; I guessed at the name. Can you post your profile.txt exported from the analyzer?

**Comment by matt-rod** [comment]
[profile.txt](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12297254/profile.txt)

**Comment by Razzmatazzz** [comment]
This is fixed in the latest release.
