### ISSUE TITLE
Archer's Crest not showing

### ISSUE THREAD

**Issue by Delusionnnn** [Razzmatazzz/RemnantSaveGuardian#57]
First character and rolled Yaesha over 50 times and Archers' Crest ring is not showing up in World Analyzer. It is still in my missing items so should be there eventually but it doesnt seem to be linked to the area properly.

**Comment by Delusionnnn** [comment]
Edit: seems to be showing under recent unreleased build in other thread. Closing thread.

**Comment by Auricrystal** [comment]
@Razzmatazzz i noticed that you added archers crest as an event under HiddenMaze, which is partially correct, its not guaranteed and thus shouldnt always be inserted as a drop, its attached to an injectible event called HiddenChamber, its an invisible wall that requires a mantle to get up a ledge and leads to an undercroft with a chest.

in short its not guaranteed.

**Comment by Razzmatazzz** [comment]
Right, which is why it will only show when the HiddenChamber tileset is present.

**Comment by Auricrystal** [comment]
curious why the route was chosen to check tilesets, does the parsing method not see the injectible events? tileset checks make sense for Losomn events as they can give dofferent rewards depending on the tileset, but this dungeon should be a simple yes or no to the HiddenChamber event, or am i not realizing something that your analyzer is accounting for?

apologies for repeating an issue already solved, just wanted to make sure what i saw in the source code was accurate.

**Comment by Razzmatazzz** [comment]
The method I'm using the parse events and get them in a reasonable order doesn't pick up HiddenChamber as an event as it doesn't appear in the same place as the other events. But it does appear in the tilesets.
