### ISSUE TITLE
After rolling back to an earlier save, World Analyzer isn't updating my Adventure Mode tab.

### ISSUE THREAD

**Issue by HongMiyo** [Razzmatazzz/RemnantSaveGuardian#58]
I believe that was the cause anyways, I rolled back to a few minutes beforehand in a Yaesha Adventure to trade the fruit instead of the box, and then continued to beat the world boss and clear a side area before going back to the ward, after rerolling Adventure mode to both Losomn and N'erud, analyzer is still showing information for that Yaesha Adventure, though, it does now know that I have the Burden of the Rebel. Save backups are still occuring.

**Comment by Razzmatazzz** [comment]
Does the latest release still have this problem?

**Comment by deadly-e** [comment]
Same issue with version .12 will try to revert to .11 and see if the issue persists.

**Comment by Razzmatazzz** [comment]
Did this involve restoring an entire save or just the world or characters?

**Comment by deadly-e** [comment]
Sorry after reading the subject again my issue seems to be slightly different. Will open a new thread to address it there. I removed my previous post from this thread. Sorry for the confusion.

**Comment by HongMiyo** [comment]
At the time I just copied my save_0.sav and profile.sav from the backup folder and put them in Remant 2's save folder, I do still have this problem on current build, the save backups do still seem to be saving properly. Nuclear option fix, I could try deleting all my save data and then touching the world stone?

**Comment by Razzmatazzz** [comment]
Wait, we're you changing the save files while the game was running?

**Comment by HongMiyo** [comment]
Oh god no.

**Comment by HongMiyo** [comment]
Oh god no.

**Comment by Razzmatazzz** [comment]
Please post your profile and world save files that aren't working here and I'll try to take a look in the next couple days.

**Comment by Razzmatazzz** [comment]
Closing this for now, but please create a new issue and post your saves there if the problem happens again.

**Comment by HongMiyo** [comment]
Sorry, I had to go out of town, I still have the issue, so I can post my save in a new post.

**Comment by HongMiyo** [comment]
Well, I feel dumb, okay, so, I went to copy my save_0.sav and and profile.sav for starting the new issue, and I noticed that there was a file named "save_0 .sav" I deleted that, launched the game, touched the worldstone, and adventure mode save analyzer worked properly again, so, it was probably just reading the wrong file. Do be aware that the file name check isn't strict if someone is dumb and messes up their file name.
