### ISSUE TITLE
Berserker crest and coffin event 

### ISSUE THREAD

**Issue by NoobbyTV** [Razzmatazzz/RemnantSaveGuardian#59]
they do not apear on the world analizer i found it in the twisted chantry u have to jump on into the coffin to kill a mini boss that reward u a mutator and behoind the stair in the water there the ring 
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/96333857/24260610-165f-495d-8254-a0b209ee5ff3)

**Comment by NoobbyTV** [comment]
[638271644181592947.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12302262/638271644181592947.zip)
wiki say it can also be found in the lament and the chimney

**Comment by Razzmatazzz** [comment]
Please use the export function of the world analyzer and provide those files.

**Comment by Razzmatazzz** [comment]
Also, what was the main event in this area? Was there a named boss?

**Comment by NoobbyTV** [comment]
the name bosswas legion  i dotnhave the backup anymore and i dont see export future sorry

**Comment by Razzmatazzz** [comment]
The export save button has an up arrow and is to the right of the character selection box on the world analyzer. If this event pops up for you again, please export your save and post in #43.
