### ISSUE TITLE
World Analyzer - Adventure Tab Not Updating

### ISSUE THREAD

**Issue by MattSr92** [Razzmatazzz/RemnantSaveGuardian#6]
After rerolling an adventure and having the game save, the new save is detected, but the adventure tab is not updated with the new data.

Edit: Closing and re-opening the program does get around this.

**Comment by Razzmatazzz** [comment]
I think I figured out the issue. You can try this development build:

[RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12198069/RemnantSaveGuardian.zip)

**Comment by MattSr92** [comment]
It doesn't seem to have fixed it.

**Comment by Toonsie** [comment]
@Razzmatazzz First off sir, would like to say thank you for trying to make this program again for this game. Secondly, I tried the development build as well and it seems like it's only "updating" after you fully restart the program, unlike the first where it used to update upon just traveling to the new re-rolled area.

**Comment by Razzmatazzz** [comment]
This might fix the not auto updating issue:
[RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12206169/RemnantSaveGuardian.zip)

@Toonsie as to those other issues, please open another issue and post your save files there.

**Comment by TesterNA** [comment]
@Razzmatazzz could you add btn for force update data or so? cause i updated to last verion and it need restart program each time i reroll new adventure(i tried tp after reroll, but its not working also)

**Comment by Razzmatazzz** [comment]
Frankly, I'd rather spend my dev time getting the auto update working.

**Comment by Frohlemageblanc** [comment]
As per the latest update, still doesn't seems to work on the auto update so far.

**Comment by Razzmatazzz** [comment]
The latest release might fix this, but I haven't been able to test thoroughly.

**Comment by Frohlemageblanc** [comment]
Nope, doesn't seems to be fixed. I still have to restart.
Steps I did try : 
- Accelerated the minutes between backups from 20 to 1.
- Waited 5 mn just in case.
- Rerolling and waiting (not working)
- Rerolling and restarting the save guardian (works)

**Comment by Razzmatazzz** [comment]
Backups have nothing to do with updating the world analyzer. The world analyzer should update anytime the game saves update. With Remnant 1, a save update was not triggered simply by re-rolling a new campaign/adventure, but you had to actually travel to trigger a save update. I don't know if that's still the case, but it could be.

**Comment by Frohlemageblanc** [comment]
Travelled every time (like in remnant 1). 
I was just trying stuff to see if the issue could arise from something else.
Indeed, closing and restarting without travelling to the location doesn't seems to update (even if in remnant 2, you can actually see where you're going on the first biome, and make some deduction about the story beforehand).

**Comment by Razzmatazzz** [comment]
This might fix it, but if not I'll have to some serious debugging tonight:
[RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12231856/RemnantSaveGuardian.zip)

**Comment by Frohlemageblanc** [comment]
Good news, the adventure tab now updates (as per the current version)

**Comment by Razzmatazzz** [comment]
Great, thanks for confirming!

**Comment by qqaazzzzaaqq** [comment]
The Adventure button doesn't work. Also, when you change the window size, the application crashes.
