### ISSUE TITLE
Can't click on adventure tab

### ISSUE THREAD

**Issue by Ratico** [Razzmatazzz/RemnantSaveGuardian#62]
I can access to Campaign and Missing items, but Adventure tab seems to be blocked... Any idea to fix it ?

**Comment by sinnoaria** [comment]
I had this issue as well, but on an older version. Did you only recently make your first adventure? If so, you need to trigger a save. Otherwise, is it on the correct character? If yes, then I am assuming that they'll ask you to upload your saves. I know that the analyzer used to be a bit weird if you have multiple characters (and even worse if you do a lot of world swapping and world copying since the analyzer doesn't seem to be prepared for that).

**Comment by Ratico** [comment]
> I had this issue as well, but on an older version. Did you only recently make your first adventure? If so, you need to trigger a save. Otherwise, is it on the correct character? If yes, then I am assuming that they'll ask you to upload your saves. I know that the analyzer used to be a bit weird if you have multiple characters (and even worse if you do a lot of world swapping and world copying since the analyzer doesn't seem to be prepared for that).

I already did some adventures before downloading the analyzer, hope the problem doesn't come from here. I'm on my main character and I don't play with the 4 others for now (but they are created)

**Comment by Razzmatazzz** [comment]
Does the campaign tab show the correct events for that character's campaign? Did you happen to create and delete any characters?

**Comment by Ratico** [comment]
> Does the campaign tab show the correct events for that character's campaign? Did you happen to create and delete any characters?

Yup, no problem with campaign on my main character, events are the same as I played
And I had one hardcore character, which I deleted to create a new one, only choose their class (same for the other characters), I didn't even travel to the first area in their campaign mode

**Comment by Razzmatazzz** [comment]
Can you export your save files via the world analyzer and post them here?

**Comment by Razzmatazzz** [comment]
Which character is experiencing this issue? First, second, third, etc.

**Comment by Ratico** [comment]
From what I know, the first, my main

**Comment by LuisBurdallo** [comment]
Happening to me using the latest version. Can't select the adventure tab. Previous version was working correctly.

**Comment by Razzmatazzz** [comment]
Feel free to revert back to the previous version while this is being worked on.

**Comment by Ratico** [comment]
> Happening to me using the latest version. Can't select the adventure tab. Previous version was working correctly.

I tried to use previous versions but the adventure tab sometimes doesn't work or events and items' names are incorrect
But I'll retry, maybe I didn't do something right

**Comment by Razzmatazzz** [comment]
Can someone experiencing this issue try this build and let me know if it works better?

[RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12317691/RemnantSaveGuardian.zip)

**Comment by Ratico** [comment]
Works for me ! Thank you a lot !

**Comment by Razzmatazzz** [comment]
Fixed in latest release.
