### ISSUE TITLE
Unclear item "Material: ThaenLeaf" listen under Missing Items

### ISSUE THREAD

**Issue by cheerbo** [Razzmatazzz/RemnantSaveGuardian#63]
This item is the only entry listed under the Materials section of Missing Items, but it's not clear what this item is. It never shows up in the world analyzer either.

**Comment by Wuxriff** [comment]
There seems to be no known usage for this item at this time. Perhaps scrapped for DLC and will drop at W13?

**Comment by Razzmatazzz** [comment]
It was included in the items list provided by AuriCrystal. They may know whether it serves any purpose currently.

**Comment by sinnoaria** [comment]
Just to check, is the Thaen Seed a different item?

**Comment by Razzmatazzz** [comment]
I don't know. If you have the Thaen Seed in your inventory, you can export it, open profile.txt, and see if `/Items/Materials/World/ThaenLeaf/Material_ThaenLeaf` appears in there.

**Comment by crackedmind** [comment]
> Just to check, is the Thaen Seed a different item?

Different. I found Thean Leaf in game resources but can't figure out where i can loot it. Looks like quest item.
May be some old item forgotten to delete, or from upcoming dlcs

Description from game
> Thaen Leaf

> This leaf feels brittle, as though the slightest touch might cause it to crumble. Yet for all that it cracks and bends, it remains whole and strong, impervious to the forces brought to bear against it.

> The World Song is created by and for all things. If life be the orchestra, then the Thaen is the conductor, stage, and theater. For the souls of all created things flow to and from the Tree of Life.
