### ISSUE TITLE
missing item 

### ISSUE THREAD

**Issue by NoobbyTV** [Razzmatazzz/RemnantSaveGuardian#66]
missing item showing thing that shouldn't be missing because they are quest item and don't reward anything i have collected everything in the game so that shouldnt be missing 
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/96333857/433668d4-81c0-4615-a727-5ead7c3880c9)

**Comment by Razzmatazzz** [comment]
That's included intentionally; see https://github.com/Razzmatazzz/RemnantSaveGuardian/issues/9#issuecomment-1666589302
