### ISSUE TITLE
Not accurate after playing coop?

### ISSUE THREAD

**Issue by merb22** [Razzmatazzz/RemnantSaveGuardian#69]
Analyzer appears to work until I join a coop game.  Then it changes what it shows and won't change back until I create a brand new adventure mode.

I'm still trying to pinpoint exactly when this issue occurs, but so far every time I've done coop and come back to a solo adventure mode, the analyzer has been inaccurate

I've joined coop without the analyzer open and with it open, and both situations appear to mess it up.  Hopefully someone else can add to this.  Still going through the worlds to see what might be happening

**Comment by Razzmatazzz** [comment]
When you're playing co-op in a friend's game, does the analyzer show your friend's events?

This might explain some of the "adventure mode tab not updating" reports. When I looked at the save file from one report, it appeared like there were three sets of events, and I wasn't sure where the third came from.

Currently, the analyzer assumes there are only two sets of events. Out of the first two sets of events, it assumes the one with more events is campaign and the other is adventure. But if one of those first two events is a campaign or adventure from joining a friend, that turns everything on its head. Might need to figure out how to tell co-op save events apart from local save events.

In Remnant 1, joining a friend's game didn't update your own local save so this wasn't something to worry about.

**Comment by Razzmatazzz** [comment]
Let me know if this works better for you:

[RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12317696/RemnantSaveGuardian.zip)

**Comment by merb22** [comment]
Thank you.  I'll try this and report back to you tomorrow.  I'll be able to test this out with a friend comparing our analyzers and our solo adventure campaign to coop ones.  Thank you

**Comment by merb22** [comment]
Hey I haven't been able to recreate the issue with that new one you posted.  Looks like my analyzer stays the same regardless of joining coop or not!  Great fix!

**Comment by Razzmatazzz** [comment]
Good to hear!
