### ISSUE TITLE
Program opens then closes 

### ISSUE THREAD

**Issue by Bastira94** [Razzmatazzz/RemnantSaveGuardian#7]
when i open the Save Guardian the Program opens for a bit i see the load icon and it closes,
it appears in the hidden tool bar but when i hover over it disappears,
i updated windows, net.6.

It worked once for a short time but bevor and after i got the same response.

![Save Guardian](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/140863076/32b7fddc-7dc7-4a6f-9d7b-749836c0343c)
![image tool bar](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/140863076/937a2699-7cdb-47fd-943b-6e2b5d77d9e2)

**Comment by Razzmatazzz** [comment]
I just uploaded a new release that fixes a lot of bugs. Does that one work for you?

**Comment by Bastira94** [comment]
That version looks to be stable for me now
