### ISSUE TITLE
Norton Antivirus interferes with saves

### ISSUE THREAD

**Issue by Dystrophy1** [Razzmatazzz/RemnantSaveGuardian#70]
Hello! First time using the save manager. I am running into the issue of the game continually loading the same save file. Any idea on how to fix this? Thanks!

**Comment by Razzmatazzz** [comment]
I'm not sure what you mean. Are you trying to restore a save via the app but then the game is replacing it with what was the latest save?

**Comment by Dystrophy1** [comment]
I used the app to check a current run. Made a single backup save and it doesn't seem like its making any new back ups. After restarting and closing the app, steam seems to only recognize that single save file and will continually reload that one regardless of what I do in game?

**Comment by Razzmatazzz** [comment]
I'm still confused about what the issue is. Do you expect it to be making more backups, but it isn't? What do you mean by steam only recognizing one save?

**Comment by Dystrophy1** [comment]
Not sure what exactly is the issue, but essentially my game is no longer saving any progress? It seems to keep loading the save file  when I ran save guardian?

**Comment by Razzmatazzz** [comment]
Every time you start the game, your progress is rolled back to the first time you used the program?

**Comment by Dystrophy1** [comment]
Yeah this seems to be the case. Unsure if its related to RSG or if its steam. The game is not saving anything at the moment

**Comment by Razzmatazzz** [comment]
Well RSG doesn't write anything to your save unless you restore a backup, so I would expect it's something to do with Steam's cloud save backup.

**Comment by Dystrophy1** [comment]
Solved for anyone running into this issue! My antivirus had some issues with RSG and for whatever reason decided to block both remnant and RSG. I added them on the allow list and all is working fine. Thanks!

**Comment by Razzmatazzz** [comment]
What antivirus are you using? I add a note.

**Comment by Dystrophy1** [comment]
Norton
