### ISSUE TITLE
Parsing the save files is complicated

### ISSUE THREAD

**Issue by Razzmatazzz** [Razzmatazzz/RemnantSaveGuardian#72]
I'm not sure if it will be possible to create a world analyzer that reliably shows all the events in a roll in a cohesive way. Once method ensures that all events are picked up, but it results in all the events being in semi-random order and it being basically impossible to tell where many of them take place. The current method works much better for ordering and grouping events, but it misses some injectable events. It's not feasible to combine these two methods. Until someone manages to come up with a magical way to parse the save files, that's where things stand.

**Comment by sinnoaria** [comment]
Would it be possible to have both for the time being with a toggle so people can choose which is the most important to them or would that be too much work?

Only thing I can think of without looking at the code itself is that perhaps someone could have it so it uses the current method as the primary, then compares with the alternative method to check for differences (such as with injectable events) and then adds them in as unsorted either by world or by campaign/adventure grouping.

**Comment by Razzmatazzz** [comment]
The latest release attempts to add back in the missing injectables. The location isn't always accurate, but at least they aren't missing.
