### ISSUE TITLE
Prevent user from exporting to same folder as the active or a backup save.

### ISSUE THREAD

**Issue by sinnoaria** [Razzmatazzz/RemnantSaveGuardian#74]
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/12928534/301279fb-cdda-4fa7-88d6-bbaa0ff93073)

**Comment by sinnoaria** [comment]
Not that I know of since I have to stop moving in the game when I export. This is the first time that exporting gave an error instead of crashing. 

Also, it still sometimes crashes if I just edited a save name recently and it makes a new backup. Not sure if that warrants a new thread since I don't really have any logs for that.

**Comment by Razzmatazzz** [comment]
Are you trying to export somewhere that already contains save files?

**Comment by Razzmatazzz** [comment]
It's a shot in the dark, but this might fix the problem:
[RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12323696/RemnantSaveGuardian.zip)

**Comment by sinnoaria** [comment]
> Are you trying to export somewhere that already contains save files?

Oh, that was probably actually the issue. It says export as plaintext, so I didn't realize it also exports a copy of the saves. I thought it was only exporting the plaintext.

**Comment by Razzmatazzz** [comment]
Yeah if you were trying to export to the same location as your save, that's not good. I should add a check for that though.
