### ISSUE TITLE
"Underground_Infection" location found

### ISSUE THREAD

**Issue by DaddyDemeyer** [Razzmatazzz/RemnantSaveGuardian#75]
After hunting down the entire biome, I was able to locate and identify the tile set Dark Conduit with "Underground Infection." I hope this feedback helps with gathering more data for future updates. Really appreciate all the time and effort you are putting towards this tool.
Looking forward to more!

![Underground_Infection](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/123812151/81f0a9aa-ab3c-4db9-a13c-69c4cafc26dc)

**Comment by Razzmatazzz** [comment]
Please post the main boss/even that occurs in that area in #45
