### ISSUE TITLE
World analyze will crash the game as well as save seem to not register.

### ISSUE THREAD

**Issue by Lurcex** [Razzmatazzz/RemnantSaveGuardian#8]
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/25150014/2fe8c923-9eea-4a68-aa08-32546497d0a6)

**Comment by cmperaza** [comment]
Also seeing the same problem. Looks like it's not honoring the users local installed path and is trying to default to `C:/Users/Dan`

**Comment by cephekt** [comment]
Also seeing the same issue. looks like the program isnt honoring the local installed path and is defaulting to using `C:\Users\Dan`. Program seems to work but the second you click on the globe it crashes for me.

**Comment by Razzmatazzz** [comment]
Where did you all purchase the game? Steam, Epic Games Store, etc...

**Comment by Razzmatazzz** [comment]
This build might fix the issue:
[RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12207246/RemnantSaveGuardian.zip)

**Comment by cephekt** [comment]
> Where did you all purchase the game? Steam, Epic Games Store, etc...

My copy is Steam. I'll check the build you just posted and report back!

**Comment by cephekt** [comment]
> This build might fix the issue: [RemnantSaveGuardian.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12207246/RemnantSaveGuardian.zip)

Looks like this fixed it. I'm able to hit the globe and it populates the list now!
