### ISSUE TITLE
Unable to select Adventure Tab in World Analyzer

### ISSUE THREAD

**Issue by deadly-e** [Razzmatazzz/RemnantSaveGuardian#83]
After installing the latest release I was able to load some previous campaigns and adventures(world only). I then performed a couple of character-only loads. When I tried to load another adventure the Adventure tab became completely inaccessible. I tried reverting to the previous version 1.0.11 and the issue persists.

**Comment by Razzmatazzz** [comment]
Does it seem like the analyzer is associating the world with the wrong character? If you select a different character in the drop down, you can check if they have the world you expect your other character to have.

**Comment by Razzmatazzz** [comment]
At any rate, I don't have the bandwidth to support issues related to restoring only character or only worlds. Those features were added to the Remnant 1 analyzer by a pull request from an outside contributor. It's already dodgy enough to associate the right character with the correct world save and this kind of mixing and matching only compounds the potential for problems.

**Comment by deadly-e** [comment]
I only have one character so not sure what to answer there. I was able to regain access to the adventure tab by loading a previous save(world only). I'll try to pay more attention to see what exactly is triggering it. Thank you for your response.

**Comment by deadly-e** [comment]
It happened again. This time I rerolled an adventure mode and the tab was accessible. I played for several hours clearing items on the list. I stopped at one point cause it was time to sleep, so I went to a stone, touched it, then closed the game. I then made sure that the last save appeared in RSG and close it also. Today I launched RSG then launched Remnant2 and the tab is not accessible.

**Comment by Razzmatazzz** [comment]
Can you post your saves here for when the adventure tab isn't working?

**Comment by deadly-e** [comment]
sure, if it happens again I will certainly do that

**Comment by Razzmatazzz** [comment]
Please re-open an issue with the saves if this happens again, but I'm closing this issue for now.
