### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by SpotifyMusic1** [Razzmatazzz/RemnantSaveGuardian#84]
Everytime I try to analyze a file a big error pops up

**Comment by Razzmatazzz** [comment]
Please go to the logs page, right click the error, click copy, and then paste it here.

**Comment by SpotifyMusic1** [comment]
Error parsing save event on

**Comment by Razzmatazzz** [comment]
Huh, that's odd. Please post the backup of your save here and I will take a look.

**Comment by SpotifyMusic1** [comment]
Its saying the website doesnt support the file type, am I maybe able to put a screenshot of the error?

**Comment by SpotifyMusic1** [comment]
![Remerror](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/142071260/b02613ee-5103-4be9-9d9d-94ed99847b86)

**Comment by Razzmatazzz** [comment]
You can put the files in a zip archive. But the problem is you're missing the game.json file in the same folder as RemnantSaveGuardian.

**Comment by SpotifyMusic1** [comment]
Hmm thats weird not sure what I did wrong

**Comment by Razzmatazzz** [comment]
It's include with every release. It's possible your antivirus deleted it for some reason, which would be weird since it's just a data file.

**Comment by SpotifyMusic1** [comment]
I just found that json file in the Saveguardian folder sooo thats even more weird

**Comment by Razzmatazzz** [comment]
Maybe try replacing it with the one from the release. It's possible it got corrupted when attempting to download a new version of it.

**Comment by SpotifyMusic1** [comment]
Ok I got it to work I needed to paste the Json file into my system32 file for some reason but oh well it worked

**Comment by Razzmatazzz** [comment]
Hmm strange sounds like windows is running the app with that as the working directory for some reason.
