### ISSUE TITLE
Underground_Infection is being loaded in but it's not actually there

### ISSUE THREAD

**Issue by 88tenyi** [Razzmatazzz/RemnantSaveGuardian#87]
Hello! Please bear with me, first time posting anything here in Github. Really a fan of your work. 

I've been trying to dig for Pulse Rifle but no luck at all, till I realized that Underground_Infection is supposed to be Dormant Nerud Facility, as others have previously pointed out. However it seems that it's showing up in the world analyzer for Nerud saves, but it's not actually there. 
![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/142136097/22b6da92-147e-4e8d-a398-3fcaebe24920)

When I first went down to the Custodian's spooky basement, there was only 1 pin slot free, and no extra barrier to open for the Pulse Rifle (Terminus is on the analyzer and it spawned normally.) 

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/142136097/4d490431-6c38-4f2e-8f53-90ac1f7383d6)

![image](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/142136097/790ff563-6ed5-4aef-865a-31576f73683a)
There's one more area here between Spectrum Nexus and The Dark Conduit, but that's just Tower of the Unseen, I just didn't bother going for a checkpoint there since I already have everything in it.

**Comment by 88tenyi** [comment]
Progeny event also appeared in Dark Conduit

**Comment by Razzmatazzz** [comment]
Location names are determined by the main event that occurs in that area. When an event can only occur in one area, then it's easy to set the location. But if an event can occur in multiple locations, it's not possible to set the location. In those instances (or when the location for a given event has not been determined), the analyzer shows the spawn table name for the area, which usually describes the area's visual appearance.

The association between the event you want and Dormant N'Erudian Facility has already been made and it will show up properly in the analyzer. This particular area in your save just shares the same visual spawn table.

**Comment by 88tenyi** [comment]
So underground_infection is likely the zombie cave, which makes sense since the cave is underground. Thank you for the insight here. I'll close this one out!
