### ISSUE TITLE
Sometimes sections disappear from the Analyzer when they no longer have missing items

### ISSUE THREAD

**Issue by AndrewSav** [Razzmatazzz/RemnantSaveGuardian#88]
[data.zip](https://github.com/Razzmatazzz/RemnantSaveGuardian/files/12328970/data.zip)
In second save (save_1) Ashen Wasteland and Whispers used to be displayed. I bought everything from Whispers and Finished Ashen Wasteland and got to Corrupted harbour, and Ashen Wasteland disappeared. Whispers too.

There are other areas in the game with no missing items, that are still shown, e.g. :
![2023-08-13_19-30-47](https://github.com/Razzmatazzz/RemnantSaveGuardian/assets/658865/71cd0a98-abec-401a-bfb3-f1ba42aec848)

What's going on here?

**Comment by Razzmatazzz** [comment]
Those are areas that are not actually present in the saves but that are added manually to display items. When there are no missing items to display, they aren't added to avoid clutter. The remnant 1 analyzer worked the same way.

**Comment by AndrewSav** [comment]
Kind of limits the usefulness of the Possible items column.
