### ISSUE TITLE
Hardcore Mode

### ISSUE THREAD

**Issue by LuisBurdallo** [Razzmatazzz/RemnantSaveGuardian#93]
I am wondering why hardcore mode isn't backed up because I got save_0.sav, save_1.sav and save_2.sav (Hardcore Character) in my Saved Games folder but it seems this tool does only back up save_0.sav and save_1.sav. Any idea?

**Comment by Razzmatazzz** [comment]
There's no reason it wouldn't backup all your save files. It literally [copies every file with the .sav extension](https://github.com/Razzmatazzz/RemnantSaveGuardian/blob/dc766cac9585f5dda4e876571e3cc1a526df4548/RemnantSaveGuardian/Views/Pages/BackupsPage.xaml.cs#L433-L440).

**Comment by LuisBurdallo** [comment]
Wait it seems the date was messed probably by me messing around with the computer's clock. You can delete this post. Sorry about that.
